### PR TITLE
feat: Add `sort` icons

### PR DESCRIPTION
**Pull request by jletey**
localhost_3000__query=sort

Related: https://github.com/feathericons/feather/issues/420, https://github.com/feathericons/feather/issues/202, https://github.com/feathericons/feather/issues/203, https://github.com/feathericons/feather/pull/668

### CODE REVIEW

**Comment by locness3** [comment]
I think we should only keep with the sort-asc-2 and sort-desc-2 tho

**Comment by jletey** [comment]
> I think we should only keep with the sort-asc-2 and sort-desc-2 tho

@locness3 Done! I'm not a huge fan of the `sort` icon, should I remove it?

**Comment by locness3** [comment]
At a very small size it looks kinda weird

**Comment by jletey** [comment]
I agree, I have removed it :)

**Comment by locness3** [comment]
Well, nice, guess we can merge

**Pull request merged**
